swagger:  "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version:      "0.1"
  title:        ISS Current Location  Integration
  description:  |
                ## Use ISS current location API to show location on a map.

                This is a Murano Service integration with
                ISS current location (https://wheretheiss.at/w/developer) to allow your Murano solution
                to get location coordinates.
  contact:
    name:       Tristan Harling
    email:      tristan.harling@ensg.eu
# documentation
externalDocs:
  description:  ISS current location documentation and other satellites!
  url:          https://wheretheiss.at/w/developer

# host:     api.wheretheiss.at
host: example.com
# basePath prefixes all resource paths
basePath: /
# tags: Categories to be referenced in documentation & marketplace
tags:
  - name:         Integration
    description:  Interface to communicate to ISS service, for the ISS current location service
schemes:
  # the ISS current location REST API is served over HTTP.
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                      Service Configuration Parameters                        #
################################################################################
x-exosite-config-parameters:
  - name: xtoken
    description: The bearer token
    type: string
    x-exosite-restricted: true
  - name:         hostdomain
    description:  Auth0 domain url
    type:         string
    required:     true
  - name:         clientidd
    description:  the client id from Auth0
    type:         string
  - name:         clientsecrett
    description:  the client secret from Auth0
    type:         string

###############
#    components
###############

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    x-exosite-prefix: Bearer
    x-exosite-from: xtoken
    x-exosite-restricted: true

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /oauth/token:
    parameters:
    - name:         hostdomain
      in:           host
      description:  specific host domain
      type:         string
      required:     true
      x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
    post:
      summary: get token for after user login,  then can access to user information.
      parameters:
        - name:         body
          in:           body
          description:  the body with all the fields
          required: true
          schema:
            $ref: "#/definitions/Bodyfortoken"
      tags:
        - calls
      operationId:  getToken
      description:  Using this path, will get an access token from auth0.
      produces:
        - application/json
      consumes:
        - application/json
      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description:  success
          schema:
              type:         object
              description: token result
              properties:              
                name:
                  description: access_token
                  type:     string

        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"
  /userinfo:
    parameters:
    - name:         hostdomain
      in:           host
      description:  specific host domain
      type:         string
      required:     true
      x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
    get:
      summary: get user info using token.
      tags:
        - calls
      operationId:  getUserInfo
      description:  Using a bearer token, wil l retrive info user from auth0.
      security:
        - Bearer: []
      produces:
      - application/json
      consumes:
        - application/json
      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description: Ok
          schema:
            $ref: "#/definitions/Success"
      
        401:
          description: error unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedError"
        403:
          description: error unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedError"
          
        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"  
################################################################################
#                                 Definitions                                  #
################################################################################

definitions:
  Success:
    type: object
    description: token result
    properties:              
      name:
        description: access_token
        type:     string
  UnauthorizedError:
    description: Access token is missing or invalid
    type: object
    properties:
      error:
        type: string
        description: not authorized
  ErrorResponse:
    description: Request error
    type: object
    properties:
      error:
        type: string
        description: Error message
      status:
        type: integer
        description: Response code
      type:
        type: string
        description: Error type
  Bodyfortoken:
    description: Body structure neede for as token
    type: object
    properties:
      grant_type:
        description: grant type config
        type: string
      clientidd:
        description: from exosite
        type: string
        x-exosite-restricted: true
      clientsecrett:
        description: from exosite2
        type: string
        x-exosite-restricted: true
      code:
        description: code  config
        type: string
      code_verifier:
        description: code verifier  config
        type: string
      redirect_uri:
        description: redirect uri  config
        type: string