swagger:  "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version:      "0.1"
  title:        ISS Current Location  Integration
  description:  |
                ## Use ISS current location API to show location on a map.

                This is a Murano Service integration with
                ISS current location (https://wheretheiss.at/w/developer) to allow your Murano solution
                to get location coordinates.
  contact:
    name:       Tristan Harling
    email:      tristan.harling@ensg.eu
# documentation
externalDocs:
  description:  ISS current location documentation and other satellites!
  url:          https://wheretheiss.at/w/developer

# host:     api.wheretheiss.at
host: example.com
# basePath prefixes all resource paths
basePath: /
# tags: Categories to be referenced in documentation & marketplace
tags:
  - name:         Integration
    description:  Interface to communicate to ISS service, for the ISS current location service
schemes:
  # the ISS current location REST API is served over HTTP.
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json


################################################################################
#                      Service Configuration Parameters                        #
################################################################################
x-exosite-config-parameters:
  - name:         Hostdomain
    description:  Auth0 domain url
    type:         string
    required:     true
  - name:         Clientid
    description:  the client id from Auth0
    type:         string
    required:     true
  - name:         Clientsecret
    description:  the client secret from Auth0
    type:         string
    required:     true


###############
#    components
###############

securityDefinitions:
  Bearer:
    type: apiKey
    scheme: Authorization
    in: header


################################################################################
#                                           Paths                              #
################################################################################
paths:
  /oauth/token:
    post:
      summary: get token for after user login,  then can access to user information.
      parameters:
        - in:           body
          name:         grant_type
          description:  what type of grant is needed
          type:         string
          required:     true
        - in:           host
          name:         Hostdomain
          description:  specific host domain
          type:         string
          required:     true
          x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
        - in:           body
          name:         Clientid
          description:  credential used for every auth0 api call
          type:         string
          required:     true
          x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
        - in:           body
          name:         Clientsecret
          description:  credential used for every auth0 api call
          type:         string
          required:     true
          x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
        - in:           body
          name:         code
          description:  code given after login callback
          type:         string
          required:     true
        - in:           body
          name:         code_verifier
          description:  specific code verifier given after callback
          type:         string
          required:     true
        - in:           body
          name:         redirect_uri
          description:  redirect url
          type:         string
          required:     true
       
      tags:
          - calls
      operationId:  getToken
      description:  Using this path, will get an access token from auth0.
      produces:
      - application/json

      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description:  success
          schema:
              type:         object
              description: token result
              properties:              
                name:
                  description: access_token
                  type:     string

        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"
  /userinfo:
    get:
      summary: get user info using token.
      parameters:
        - in:           body
          name:         grant_type
          description:  what type of grant is needed
          type:         string
          required:     true
        - in:           host
          name:         Hostdomain
          description:  specific host domain
          type:         string
          required:     true
          x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
      tags:
        - calls
      operationId:  getUserInfo
      description:  Using a bearer token, wil l retrive info user from auth0.
      security:
        - Bearer: []
      produces:
      - application/json

      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description:  success
          schema:
              type:         object
              description: token result
              properties:              
                name:
                  description: access_token
                  type:     string
        401:
          description: unauthorized
          $ref: "#/definitions/UnauthorizedError"
        403:
          description: unauthorized
          $ref: "#/definitions/UnauthorizedError"
          
        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"  
################################################################################
#                                 Definitions                                  #
################################################################################

definitions:
  UnauthorizedError:
    description Access token is missing or invalid
  ErrorResponse:
    description: Request error
    type: object
    properties:
      error:
        type: string
        description: Error message
      status:
        type: integer
        description: Response code
      type:
        type: string
        description: Error type