swagger:  "2.0"
################################################################################
#                              API Information                                 #
################################################################################
info:
  version:      "0.1"
  title:        Auth0  Integration
  description:  |
                ## Use  API to Auth0.
                This is a Murano Service integration with
  contact:
    name:       Tristan Harling
    email:      tristan.harling@ensg.eu
# documentation
externalDocs:
  description:  doc from exosite
  url:          https://docs.exosite.com
# host:     api.wheretheiss.at
host: example.com
# basePath prefixes all resource paths
basePath: /
# tags: Categories to be referenced in documentation & marketplace
tags:
  - name:         Integration
    description:  Interface to communicate to ISS service, for the ISS current location service
schemes:
  # the ISS current location REST API is served over HTTP.
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json

###############
#    components
###############

securityDefinitions:
  Bearer:
    type: bearer
    name: xtoken
    #important
    description: bearer that is delivered by auth0 after ask token. Can be user after to get userinfo
    x-exosite-restricted: true

################################################################################
#                      Service Configuration Parameters                        #
################################################################################
x-exosite-config-parameters:
  - name: xtoken
    description: The bearer token
    type: string
    x-exosite-restricted: true
  - name:         hostdomain
    description:  Auth0 domain url
    type:         string
    required:     true
  - name:         client_id
    description:  the client id from Auth0
    type:         string
  - name:         client_secret
    description:  the client secret from Auth0
    format:       password
    type:         string

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /oauth/token:
    parameters:
    - name:         hostdomain
      in:           host
      description:  specific host domain
      type:         string
      required:     true
      x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
    post:
      summary: get token for after user login,  then can access to user information.
      parameters:
        - name:         body
          in:           body
          description:  the body with all the fields
          required: true
          schema:
            $ref: "#/definitions/Bodyfortoken"
        # - name:         client_id
        #   description:  domain credential
        #   in:           query
        #   type:         string
        #   x-exosite-restricted: true
        #   required: true
        # - name:         client_secret
        #   description:  domain credential for secret code
        #   in:           query
        #   type:         string
        #   x-exosite-restricted: true
        #   required:    true
        # - name:         code
        #   description:  code  config
        #   in:           query
        #   type:         string
        #   required:     true
        # - name:         code_verifier
        #   description:  code verifier  config
        #   in:           query
        #   type:         string
        #   required:     true
        # - name:         redirect_uri
        #   description:  redirect uri  config
        #   in:           query
        #   type:         string
        #   required:     true
        # - name:         grant_type
        #   type:         string
        #   in:           query
        #   description:  the grant_type that will be used to perform future user request
        #   required:     true
      tags:
        - calls
      operationId:  getToken
      description:  Using this path, will get an access token from auth0.
      security:    []
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description:  success
          schema:
            $ref: "#/definitions/Token"

        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"
  /userinfo:
    parameters:
    - name:         hostdomain
      in:           host
      description:  specific host domain
      type:         string
      required:     true
      x-exosite-restricted: true # Indicate the Scripting call cannot overload this parameter
    get:
      summary: get user info using token.
      tags:
        - calls
      operationId:  getUserInfo
      description:  Using a bearer token, wil l retrive info user from auth0.
      security:
        - Bearer: []
      produces:
      - application/json
      consumes:
        - application/json
      x-exosite-example:    |
                      --#ENDPOINT GET /satellites/iss
  
                      Iss_data = Iss-now({id=25544})

                      print(to_json(Iss_data))

                      response.message = Iss_data
      responses:
        200:
          description: Ok
          schema:
            $ref: "#/definitions/Success"
      
        401:
          description: error unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedError"
        403:
          description: error unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedError"
          
        default:
          description: error
          schema:
            $ref:       "#/definitions/ErrorResponse"  
################################################################################
#                                 Definitions                                  #
################################################################################

definitions:
  Token:
    type:     object
    description: a token acess and metadata
    properties:              
      access_token:
        description: access of token
        type:     string
      token_type:
        description: type of token
        type: string
      expires_in:
        description: date of expiration
        type: integer
  Success:
    type: object
    description: user info result
  UnauthorizedError:
    description: Access token is missing or invalid
    type: object
    properties:
      error:
        type: string
        description: not authorized
  ErrorResponse:
    description: Request error
    type: object
    properties:
      error:
        type: string
        description: Error message
      status:
        type: integer
        description: Response code
      type:
        type: string
        description: Error type
  Bodyfortoken:
    description: Body structure needed for as token
    type: object
    properties:
      grant_type:
        description: grant type config
        type: string
      client_id:
        type: string
        x-exosite-restricted: true
      client_secret:
        type: string
        x-exosite-restricted: true
      code:
        description: code  config
        type: string
      code_verifier:
        description: code verifier  config
        type: string
      redirect_uri:
        description: redirect uri  config
        type: string